### ISSUE TITLE
NameError: name 'env_idx' is not defined

### ISSUE THREAD

**Issue by zzzzcl** [SimarKareer/ViNL#8]
Hi Simar! Your work is excellent!! And I am tring to reproduce the code of "VinL". But when I tried to use the obstacle orriented walking policy trained by myself,following the instruction in python legged_gym/scripts/train.py --task=aliengo_lbc.

Traceback (most recent call last):
  File "legged_gym/scripts/train.py", line 55, in <module>
    train(args)
  File "legged_gym/scripts/train.py", line 43, in train
    env, env_cfg = task_registry.make_env(name=args.task, args=args)
  File "/home/orange/2411/ViNL-master/legged_gym/utils/task_registry.py", line 117, in make_env
    env = task_class(
  File "/home/orange/2411/ViNL-master/legged_gym/envs/aliengo/aliengo.py", line 124, in __init__
    self.envs[env_idx], self.actor_handles[env_idx], "base"
NameError: name 'env_idx' is not defined

I don't know how to solve this problem and look forward to getting your help, thanks!

**Comment by lattaai5** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the Aliengo class initialization to correctly handle camera setup for each environment. Replaced the undefined 'env_idx' with the loop variable 'i'.

I also created pull request: https://github.com/SimarKareer/ViNL/pull/9


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
